channels:
  - conda-forge
dependencies:
  - appmode
  - ipyvuetify
  - ipywidgets
  - seaborn
  - pandas
  - demjson
  - numpy
  - ipywidgets
  - tensorflow
  - appmode
  - scikit-learn
  - ipympl
  - ipyvuetify
  - matplotlib
